# Generated by Django 5.1.1 on 2024-10-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("imagen", models.URLField()),
                ("descripcion", models.TextField()),
                ("profesor", models.CharField(max_length=100)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cupo", models.IntegerField()),
            ],
        ),
    ]
